[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []

[lib]
name = "osm_gps_map_sys"

[package]
build = "build.rs"
links = "osm_gps_map"
name = "osm-gps-map-sys"
version = "0.2.0"
